version: "3.5"

services:
  #postgres service
  mariadb:
    container_name: mariadb_container
    build: ./mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-myadmin123}
      MYSQL_DATABASE: myNameDB
 
    volumes:
      - ./mariadb-data:/var/lib/mysql
      # - ./backup/data.backup:/data/data.backup
    networks:
      myNet: 
        ipv4_address: 172.16.238.10
    restart: unless-stopped
 #localhost:5050
  phpmyadmin:
    container_name: phpmyadmin_container
    build: ./phpmyadmin
    environment:
      PMA_HOST: mariadb
      #PMA_ARBITRARY: 1

    ports:
      - "${ADMIN_PORT:-8088}:80"
    networks:
      myNet: 
        ipv4_address: 172.16.238.11
    restart: unless-stopped
    depends_on: 
      - mariadb 
  tomcat:
    container_name: tomcat8.5
    build: ./tomcat
    ports:
      - "${TOMCAT_PORT:-8080}:8080"
      - "${TOMCAT_AJP:-8009}:8009"
    volumes:
      - ./tomcat-webapps:/usr/local/tomcat/webapps
    networks:
      myNet: 
        ipv4_address: 172.16.238.12
    restart: unless-stopped

networks:
  myNet:
    ipam: 
      driver: default
      config:
        - subnet: "172.16.238.0/24"

#volumes:
  #  postgres:
 # pgadmin:
#  webapps:./tomcat-webapps
